#include "dragonessEssentialVars.h"
char* dragonessDebugLogPrefix = "Engine: ";
bool dragonessBoolShaderCompilationFailed = false;
GLuint programID;
GLuint matrixID;
GLFWwindow* window;
int antialiasing = 4;
int windowLength = 1920;
int windowHeight = 1080;
GLuint vertexArrayID;
int nbFrames = 0;
float deltaTime;
float horizontalAngle = 180.0f;
float verticalAngle = -1.6f;
float initialFOV = 45.0f;
float keyboardSpeed = 3.0f;
float mouseSpeed = 0.5f;
double currentTime;
double lastTime;
double deltaLastTime;
mat4 viewMatrix;
mat4 projectionMatrix;
mat4 modelMatrix;
vec3 position = {0,0,0};
mat4 mvp;
float dragonessDebugColorCounter = 0.0f;
GLuint vertexBuffer;
GLuint colorBuffer;
GLuint textureBuffer;
